# Generated by Django 4.2 on 2025-04-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hashtag",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="user.hashtag"
            ),
        ),
    ]
