# Generated by Django 4.2 on 2025-04-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_ordinary_user",
            field=models.BooleanField(default=False),
        ),
    ]
